### ISSUE TITLE
[SAML] timeout behind http proxy

### ISSUE THREAD

**Issue by bartleboeuf** [openanalytics/containerproxy#48] opened 2021-02-04 11:27 UTC
Hi,

Would it be possible to implement the management of the http proxy on SAML calls, because we are running into a timeout on authentication with our AzureAD. Thank you.

Here the part of the logs 

```
2021-02-04 09:51:05.250 DEBUG 1 --- [           main] o.s.s.saml.metadata.MetadataManager      : Created new trust manager for metadata provider org.opensaml.saml2.metadata.provider.HTTPMetadataProvider@397ef2
2021-02-04 09:51:05.250 DEBUG 1 --- [           main] o.s.s.saml.metadata.MetadataManager      : Adding signature filter
2021-02-04 09:51:05.250 DEBUG 1 --- [           main] o.s.s.saml.metadata.MetadataManager      : Initializing extendedMetadataDelegate org.opensaml.saml2.metadata.provider.HTTPMetadataProvider@397ef2
2021-02-04 09:51:05.250 DEBUG 1 --- [           main] o.s.s.s.m.ExtendedMetadataDelegate       : Initializing delegate
2021-02-04 09:51:05.287 DEBUG 1 --- [           main] .s.m.p.AbstractReloadingMetadataProvider : Beginning refresh of metadata from 'https://login.microsoftonline.com/aca3c8d6-aa71-4e1a-a10e-xxxxxxxxx/FederationMetadata/2007-06/FederationMetadata.xml'
2021-02-04 09:51:05.304 DEBUG 1 --- [           main] o.o.s.m.provider.HTTPMetadataProvider    : Attempting to fetch metadata document from 'https://login.microsoftonline.com/aca3c8d6-aa71-4e1a-a10e-xxxxxxxxx/FederationMetadata/2007-06/FederationMetadata.xml'
2021-02-04 09:51:05.310 DEBUG 1 --- [           main] o.a.commons.httpclient.HttpConnection    : Open connection to login.microsoftonline.com:443
...
2021-02-04 09:53:16.106 DEBUG 1 --- [           main] o.a.c.httpclient.HttpMethodDirector      : Closing the connection.
2021-02-04 09:53:16.106  INFO 1 --- [           main] o.a.c.httpclient.HttpMethodDirector      : I/O exception (java.net.ConnectException) caught when processing request: Connection timed out (Connection timed out)
2021-02-04 09:53:16.112 DEBUG 1 --- [           main] o.a.c.httpclient.HttpMethodDirector      : Connection timed out (Connection timed out)
java.net.ConnectException: Connection timed out (Connection timed out)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:na]
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:na]
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:na]
        at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:na]
        at java.base/java.net.SocksSocketImpl.connect(Unknown Source) ~[na:na]
        at java.base/java.net.Socket.connect(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.<init>(Unknown Source) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketFactoryImpl.createSocket(Unknown Source) ~[na:na]
        at org.opensaml.ws.soap.client.http.TLSProtocolSocketFactory.createSocket(TLSProtocolSocketFactory.java:185) ~[openws-1.5.6.jar!/:na]
        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707) ~[commons-httpclient-3.1.jar!/:na]
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387) ~[commons-httpclient-3.1.jar!/:na]
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171) ~[commons-httpclient-3.1.jar!/:na]
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397) ~[commons-httpclient-3.1.jar!/:na]
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323) ~[commons-httpclient-3.1.jar!/:na]
        at org.opensaml.saml2.metadata.provider.HTTPMetadataProvider.fetchMetadata(HTTPMetadataProvider.java:250) ~[opensaml-2.6.6.jar!/:na]
        at org.opensaml.saml2.metadata.provider.AbstractReloadingMetadataProvider.refresh(AbstractReloadingMetadataProvider.java:258) ~[opensaml-2.6.6.jar!/:na]
        at org.opensaml.saml2.metadata.provider.AbstractReloadingMetadataProvider.doInitialization(AbstractReloadingMetadataProvider.java:239) ~[opensaml-2.6.6.jar!/:na]
        at org.opensaml.saml2.metadata.provider.AbstractMetadataProvider.initialize(AbstractMetadataProvider.java:407) ~[opensaml-2.6.6.jar!/:na]
        at org.springframework.security.saml.metadata.ExtendedMetadataDelegate.initialize(ExtendedMetadataDelegate.java:167) ~[spring-security-saml2-core-1.0.10.RELEASE.jar!/:1.0.10.RELEASE]
```

Note : we found this on spring security doc but no way apply it (https://docs.spring.io/spring-security-saml/docs/current/reference/html/configuration-advanced.html#artifact-resolution)

Thanks

**Comment by LEDfan** [comment] 2021-02-10 08:45
Hi @bartleboeuf 

I'm not sure whether I understand your question completely. Do you want to use a proxy to connect to your IDP (`https://login.microsoftonline.com`) or do you want to configure the timeout to connect to your IDP? Or a combination of these?
When you want to use a proxy for a Java application you typically use something like:

```
java -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=3128   -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=3128 ...
```

For configuring the timeout we would need to add a bit of code for configuring that.

**Comment by hmissi** [comment] 2021-02-11 09:04
I have the same issue, and I added the java `-Dhttp.proxyHost = ... `but that doesn't change anything! I also have `java.net.ConnectException: Connection timed out (Connection timed out)`

un issue similaire sur metadata loading timeout https://stackoverflow.com/questions/22489065/saml-service-provider-spring-security

**Comment by hmissi** [comment] 2021-02-11 15:35
`2021-02-11 15:33:33.396 DEBUG 7 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'samlEntryPoint'
2021-02-11 15:33:33.396 DEBUG 7 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'SAMLConfiguration'
2021-02-11 15:33:33.408 DEBUG 7 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'defaultWebSSOProfileOptions'
2021-02-11 15:33:33.425 DEBUG 7 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'webSSOprofile'
2021-02-11 15:33:33.437 DEBUG 7 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'metadata'
2021-02-11 15:33:33.438 DEBUG 7 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'idpMetadata'
2021-02-11 15:33:33.438 DEBUG 7 --- [           main] o.s.c.e.PropertySourcesPropertyResolver  : Found key 'proxy.saml.idp-metadata-url' in PropertySource 'configurationProperties' with value of type String
2021-02-11 15:33:33.448 DEBUG 7 --- [           main] o.apache.commons.httpclient.HttpClient   : Java version: 11.0.10
2021-02-11 15:33:33.448 DEBUG 7 --- [           main] o.apache.commons.httpclient.HttpClient   : Java vendor: Oracle Corporation
2021-02-11 15:33:33.448 DEBUG 7 --- [           main] o.apache.commons.httpclient.HttpClient   : Java class path: /opt/shinyproxy/shinyproxy.jar
2021-02-11 15:33:33.448 DEBUG 7 --- [           main] o.apache.commons.httpclient.HttpClient   : Operating system name: Linux
2021-02-11 15:33:33.448 DEBUG 7 --- [           main] o.apache.commons.httpclient.HttpClient   : Operating system architecture: amd64
2021-02-11 15:33:33.448 DEBUG 7 --- [           main] o.apache.commons.httpclient.HttpClient   : Operating system version: 4.14.209-160.339.amzn2.x86_64
2021-02-11 15:33:33.450 DEBUG 7 --- [           main] o.apache.commons.httpclient.HttpClient   : SUN 11.0: SUN (DSA key/parameter generation; DSA signing; SHA-1, MD5 digests; SecureRandom; X.509 certificates; PKCS12, JKS & DKS keystores; PKIX CertPathValidator; PKIX CertPathBuilder; LDAP, Collection CertStores, JavaPolicy Policy; JavaLoginConfig Configuration)
2021-02-11 15:33:33.450 DEBUG 7 --- [           main] o.apache.commons.httpclient.HttpClient   : SunRsaSign 11.0: Sun RSA signature provider
2021-02-11 15:33:33.450 DEBUG 7 --- [           main] o.apache.commons.httpclient.HttpClient   : SunEC 11.0: Sun Elliptic Curve provider (EC, ECDSA, ECDH)
2021-02-11 15:33:33.450 DEBUG 7 --- [           main] o.apache.commons.httpclient.HttpClient   : SunJSSE 11.0: Sun JSSE provider(PKCS12, SunX509/PKIX key/trust factories, SSLv3/TLSv1/TLSv1.1/TLSv1.2/TLSv1.3/DTLSv1.0/DTLSv1.2)
2021-02-11 15:33:33.450 DEBUG 7 --- [           main] o.apache.commons.httpclient.HttpClient   : SunJCE 11.0: SunJCE Provider (implements RSA, DES, Triple DES, AES, Blowfish, ARCFOUR, RC2, PBE, Diffie-Hellman, HMAC, ChaCha20)
2021-02-11 15:33:33.450 DEBUG 7 --- [           main] o.apache.commons.httpclient.HttpClient   : SunJGSS 11.0: Sun (Kerberos v5, SPNEGO)
2021-02-11 15:33:33.450 DEBUG 7 --- [           main] o.apache.commons.httpclient.HttpClient   : SunSASL 11.0: Sun SASL provider(implements client mechanisms for: DIGEST-MD5, EXTERNAL, PLAIN, CRAM-MD5, NTLM; server mechanisms for: DIGEST-MD5, CRAM-MD5, NTLM)
2021-02-11 15:33:33.450 DEBUG 7 --- [           main] o.apache.commons.httpclient.HttpClient   : XMLDSig 11.0: XMLDSig (DOM XMLSignatureFactory; DOM KeyInfoFactory; C14N 1.0, C14N 1.1, Exclusive C14N, Base64, Enveloped, XPath, XPath2, XSLT TransformServices)
2021-02-11 15:33:33.450 DEBUG 7 --- [           main] o.apache.commons.httpclient.HttpClient   : SunPCSC 11.0: Sun PC/SC provider
2021-02-11 15:33:33.450 DEBUG 7 --- [           main] o.apache.commons.httpclient.HttpClient   : JdkLDAP 11.0: JdkLDAP Provider (implements LDAP CertStore)
2021-02-11 15:33:33.450 DEBUG 7 --- [           main] o.apache.commons.httpclient.HttpClient   : JdkSASL 11.0: JDK SASL provider(implements client and server mechanisms for GSSAPI)
2021-02-11 15:33:33.450 DEBUG 7 --- [           main] o.apache.commons.httpclient.HttpClient   : SunPKCS11 11.0: Unconfigured and unusable PKCS11 provider
2021-02-11 15:33:33.454 DEBUG 7 --- [           main] o.a.c.h.params.DefaultHttpParams         : Set parameter http.useragent = Jakarta Commons-HttpClient/3.1
2021-02-11 15:33:33.455 DEBUG 7 --- [           main] o.a.c.h.params.DefaultHttpParams         : Set parameter http.protocol.version = HTTP/1.1
2021-02-11 15:33:33.457 DEBUG 7 --- [           main] o.a.c.h.params.DefaultHttpParams         : Set parameter http.connection-manager.class = class org.apache.commons.httpclient.SimpleHttpConnectionManager
2021-02-11 15:33:33.457 DEBUG 7 --- [           main] o.a.c.h.params.DefaultHttpParams         : Set parameter http.protocol.cookie-policy = default
2021-02-11 15:33:33.457 DEBUG 7 --- [           main] o.a.c.h.params.DefaultHttpParams         : Set parameter http.protocol.element-charset = US-ASCII
2021-02-11 15:33:33.457 DEBUG 7 --- [           main] o.a.c.h.params.DefaultHttpParams         : Set parameter http.protocol.content-charset = ISO-8859-1
2021-02-11 15:33:33.458 DEBUG 7 --- [           main] o.a.c.h.params.DefaultHttpParams         : Set parameter http.method.retry-handler = org.apache.commons.httpclient.DefaultHttpMethodRetryHandler@6ffa56fa
2021-02-11 15:33:33.458 DEBUG 7 --- [           main] o.a.c.h.params.DefaultHttpParams         : Set parameter http.dateparser.patterns = [EEE, dd MMM yyyy HH:mm:ss zzz, EEEE, dd-MMM-yy HH:mm:ss zzz, EEE MMM d HH:mm:ss yyyy, EEE, dd-MMM-yyyy HH:mm:ss z, EEE, dd-MMM-yyyy HH-mm-ss z, EEE, dd MMM yy HH:mm:ss z, EEE dd-MMM-yyyy HH:mm:ss z, EEE dd MMM yyyy HH:mm:ss z, EEE dd-MMM-yyyy HH-mm-ss z, EEE dd-MMM-yy HH:mm:ss z, EEE dd MMM yy HH:mm:ss z, EEE,dd-MMM-yy HH:mm:ss z, EEE,dd-MMM-yyyy HH:mm:ss z, EEE, dd-MM-yyyy HH:mm:ss z]
2021-02-11 15:33:33.461 DEBUG 7 --- [           main] .s.m.p.AbstractReloadingMetadataProvider : Using ctor arg-supplied background task Timer instance
2021-02-11 15:33:33.463 DEBUG 7 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'parserPool'
2021-02-11 15:33:33.463 DEBUG 7 --- [           main] o.o.xml.parse.StaticBasicParserPool      : Setting DocumentBuilderFactory attribute 'http://javax.xml.XMLConstants/feature/secure-processing'
2021-02-11 15:33:33.463 DEBUG 7 --- [           main] o.o.xml.parse.StaticBasicParserPool      : Setting DocumentBuilderFactory attribute 'http://apache.org/xml/features/disallow-doctype-decl'
2021-02-11 15:33:33.465 DEBUG 7 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'extendedMetadata'
2021-02-11 15:33:33.483 DEBUG 7 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'keyManager'
2021-02-11 15:33:33.486 DEBUG 7 --- [           main] o.s.s.saml.metadata.MetadataManager      : Creating metadata reload timer with interval 10000
2021-02-11 15:33:33.487 DEBUG 7 --- [           main] o.s.s.saml.metadata.MetadataManager      : Clearing metadata cache
2021-02-11 15:33:33.487 DEBUG 7 --- [           main] o.s.s.saml.metadata.MetadataManager      : Reloading metadata
2021-02-11 15:33:33.487 DEBUG 7 --- [           main] o.s.s.saml.metadata.MetadataManager      : Refreshing metadata provider org.opensaml.saml2.metadata.provider.HTTPMetadataProvider@3fbcfe81
2021-02-11 15:33:33.487 DEBUG 7 --- [           main] o.s.s.saml.metadata.MetadataManager      : Trust verification skipped for metadata provider org.opensaml.saml2.metadata.provider.HTTPMetadataProvider@3fbcfe81
2021-02-11 15:33:33.490 DEBUG 7 --- [           main] o.s.s.saml.metadata.MetadataManager      : Created new trust manager for metadata provider org.opensaml.saml2.metadata.provider.HTTPMetadataProvider@3fbcfe81
2021-02-11 15:33:33.490 DEBUG 7 --- [           main] o.s.s.saml.metadata.MetadataManager      : Adding signature filter
2021-02-11 15:33:33.490 DEBUG 7 --- [           main] o.s.s.saml.metadata.MetadataManager      : Initializing extendedMetadataDelegate org.opensaml.saml2.metadata.provider.HTTPMetadataProvider@3fbcfe81
2021-02-11 15:33:33.490 DEBUG 7 --- [           main] o.s.s.s.m.ExtendedMetadataDelegate       : Initializing delegate
2021-02-11 15:33:33.544 DEBUG 7 --- [           main] .s.m.p.AbstractReloadingMetadataProvider : Beginning refresh of metadata from 'https://login.microsoftonline.com/aca3c8d6-aa71-4e1a-a10e-03572fc58c0b/FederationMetadata/2007-06/FederationMetadata.xml'
2021-02-11 15:33:33.562 DEBUG 7 --- [           main] o.o.s.m.provider.HTTPMetadataProvider    : Attempting to fetch metadata document from 'https://login.microsoftonline.com/aca3c8d6-aa71-4e1a-a10e-03572fc58c0b/FederationMetadata/2007-06/FederationMetadata.xml'
2021-02-11 15:33:33.568 DEBUG 7 --- [           main] o.a.commons.httpclient.HttpConnection    : Open connection to login.microsoftonline.com:443
2021-02-11 15:33:53.001 DEBUG 7 --- [tiveProxyKiller] o.s.c.e.PropertySourcesPropertyResolver  : Found key 'proxy.admin-groups' in PropertySource 'configurationProperties' with value of type String
`

**Comment by bartleboeuf** [comment] 2021-02-11 16:27
Hi @LEDfan ,

We tried to launch shinyproxy with our web proxy to get access to the IDP. But we fall everytime on "`java.net.ConnectException: Connection timed out (Connection timed out)`".

Here our java cmdline with the proxy setting. 
`
java -Dhttp.proxyHost=web-proxy.mydomainaws.local -Dhttp.proxyPort=3128 -Dhttp.nonProxyHosts="172.20.0.1|10.24.224.*|10.24.225.*|localhost|127.*|[::1]|169.254.169.254" -Dhttps.proxyHost=web-proxy.mydomainaws.local -Dhttps.proxyPort=3128 -jar /opt/shinyproxy/shinyproxy.jar
`

**Comment by hmissi** [comment] 2021-02-23 09:41
Hi @LEDfan 
do you have any solutions please.
I am stuck to implement the shinyproxy...

**Comment by LEDfan** [comment] 2021-02-25 14:33
Hi @bartleboeuf 

This seems to be more of Java/Network problem than something within ShinyProxy. I would try to further debug this:
 - are you sure your proxy is a HTTP and not e.g. a SOCKS proxy?
 - can you reach the proxy from the ShinyProxy host, e.g. try to reach it with `telnet`
 - can you use the proxy using `curl`?  i.e. try to do a request to the web using the proxy: https://oxylabs.io/blog/curl-with-proxy
 - ...

**Comment by LEDfan** [comment] 2021-02-25 15:14
Hi @hmissi 

It's not clear to me what you are trying to do. Do your network setup requires you to use a proxy, or are you just experiencing timeouts and trying to solve that by using a proxy? In the first case, please follow the same steps as above. In the second case: you won't be able to solve ConnectException by adding proxy options. Instead you should try to find out why ShinyProxy is unable to contact the SAML metadata URL. ShinyProxy tries to connect to the SAML server for about two minutes, if that fails the following messages should be logged:
```
2021-02-25 16:09:33.995  INFO 111992 --- [           main] o.a.c.httpclient.HttpMethodDirector      : I/O exception (java.net.ConnectException) caught when processing request: Connection timed out (Connection timed out)
2021-02-25 16:09:33.996  INFO 111992 --- [           main] o.a.c.httpclient.HttpMethodDirector      : Retrying request
````

Please try the following things to debug the issue
 - make sure you are using the correct SAML IDP metadata URL
 - can you reach the server hosting the metadata using telnet?
 - can you download the metadata on the ShinyProxy server using curl?
 - how long does that take (use the `time` command)?
 - if it takes unusual long, is that normal? If not, what is slowing down the request? Maybe resolving of the domainname (DNS)?
 
Success!

**Comment by hmissi** [comment] 2021-03-08 12:20
Hi @LEDfan 
I took the version corrected by @bartleboeuf and it worked.
I confirm that the problem is that the SAML authentication class does not support proxy exports
Thanks @bartleboeuf

**Comment by LEDfan** [comment] 2021-11-05 13:11
The changes proposed in #50 are now part of [ShinyProxy 2.6.0](https://shinyproxy.io/downloads/#260) (ContainerProxy 0.8.10). Therefore I believe this issue is solved.

Feel free to re-open the issue if you still encounter an issue with it.

**Closed by LEDfan** 2021-11-05 13:11 UTC
Labels: question
