### ISSUE TITLE
OpenId Refresh token is not passed as container variable

### ISSUE THREAD

**Issue by rutgerzoontjens** [openanalytics/containerproxy#65] opened 2022-05-10 14:09 UTC
Hi,
I am trying to pass the Refresh Token variable to a pod, but have not yet been successful.

Setup:

Shinyproxy 2.6.0 running in a pod on an Azure Kubernetes cluster
Openid authentication
Scope: {appid}/.default
the container variable is added to the app in the application yml:
container-env: SHINYPROXY_REFRESH_TOKEN: “#{oidcUser.refreshToken}”

Problem is that the Refresh Token value stays empty when running the pod.

Does anyone know how to fix this?

Thanks in advance!
Rutger

**Comment by LEDfan** [comment] 2022-05-16 07:11
Hi

Recently, we are getting more reports of issues with this feature, although we are using it in many deployments ourselves, without any issue. Because this issue is harder to debug, I created a special snapshot of ShinyProxy with a few changes in order to make things easier.

Can you try deploying this Docker image `openanalytics/shinyproxy-snapshot:2.6.1-SNAPSHOT-20220516.085208` and provide the answers to these steps/questions:

1. go to the page `/debug-spel` on your shinyproxy server, e.g. `https://shinyproxy-demo.local/debug-spel`. This page shows a JSON serialization of all objects that can be used in the SpEL expressions. For example, when using OIDC, it should show a non-null `oidcUser` object. 
2. check whether this object contains the properties you are trying to access. For example, in the case of @rutgerzoontjens this will be the `refreshToken` property. Please report back whether this property is included in this object or not.
3. try opening an app for which you have the SpEL config defined. In the logs of ShinyProxy, you now should see something like:
   ```
2022-05-16 07:00:41.799  INFO 1 --- [  XNIO-1 task-1] e.o.c.s.e.SpecExpressionResolver         : Resolved SpEL expression:
	INPUT:	#{oidcUser.refreshToken}
	OUTPUT:	eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUI
   ```
5. Please provide me with these logs (remove any sensitive values). You can check already whether the output contains the correct expression.
6. Provide me with the following additional information:
  - Identity Provider (e.g. Keycloak, Azure AD, Okta ...)
  - Which container backend you are using (Docker, Docker swarm, Kubernetes). Please report the version as well.
  - Are you always experiencing the issue, or does it sometimes work?
  - Provide your full `application.yml`, you can strip out any non-relevant apps or sensitive values. But since I cannot reproduce the issue, I'm starting to think there may be some issue in the config (or parsing of it).

Let's hope we can resolve this issue using the provided information!

**Comment by LEDfan** [comment] 2024-01-02 08:58
Hi  @rutgerzoontjens , we noticed that for Azure B2C you need add the specify the `offline_access`  scope in order to get a refresh token. Can you try this out? See https://github.com/openanalytics/shinyproxy/issues/464

**Comment by rutgerzoontjens** [comment] 2024-01-04 10:13
Hi Tobia,
Yes, it works!
Rutger

Op di 2 jan 2024 om 09:58 schreef Tobia De Koninck ***@***.***

**Comment by LEDfan** [comment] 2024-01-08 12:46
That's great news! Since I think the problem is solved now, I'm going to close this issue. Feel free to open a new issue in case you have any problems or suggestions.

**Closed** 2024-05-07 13:02 UTC
Labels: question
